#!/usr/bin/env bash
set -e

if [[ "$ACCOUNT_DB_USER" != "$POSTGRES_USER" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE USER "$ACCOUNT_DB_USER" WITH PASSWORD ''$ACCOUNT_DB_PASSWORD'''
    WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$ACCOUNT_DB_USER')\gexec
EOSQL
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  SELECT 'CREATE DATABASE "$ACCOUNT_DB" OWNER "$ACCOUNT_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$ACCOUNT_DB')\gexec
  GRANT ALL PRIVILEGES ON DATABASE "$ACCOUNT_DB" TO "$ACCOUNT_DB_USER";

  CREATE USER "$KEYCLOAK_DB_USER" WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
  CREATE DATABASE "$KEYCLOAK_DB" OWNER "$KEYCLOAK_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB" TO "$KEYCLOAK_DB_USER";
EOSQL
