#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$KEYCLOAK_DB_USER" WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
  CREATE DATABASE "$KEYCLOAK_DB" OWNER "$KEYCLOAK_DB_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB" TO "$KEYCLOAK_DB_USER";
EOSQL
