#!/usr/bin/env bash
set -e

if [[ "$ACCOUNT_DB_USER" != "$POSTGRES_USER" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE USER "$ACCOUNT_DB_USER" WITH PASSWORD ''$ACCOUNT_DB_PASSWORD'''
    WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$ACCOUNT_DB_USER')\gexec
EOSQL
fi

if [[ "$CATALOG_DB_USER" != "$POSTGRES_USER" && "$CATALOG_DB_USER" != "$ACCOUNT_DB_USER" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE USER "$CATALOG_DB_USER" WITH PASSWORD ''$CATALOG_DB_PASSWORD'''
    WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$CATALOG_DB_USER')\gexec
EOSQL
fi

if [[ "$ORDER_DB_USER" != "$POSTGRES_USER" && "$ORDER_DB_USER" != "$ACCOUNT_DB_USER" && "$ORDER_DB_USER" != "$CATALOG_DB_USER" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE USER "$ORDER_DB_USER" WITH PASSWORD ''$ORDER_DB_PASSWORD'''
    WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$ORDER_DB_USER')\gexec
EOSQL
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  SELECT 'CREATE DATABASE "$ACCOUNT_DB" OWNER "$ACCOUNT_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$ACCOUNT_DB')\gexec
  GRANT ALL PRIVILEGES ON DATABASE "$ACCOUNT_DB" TO "$ACCOUNT_DB_USER";

  SELECT 'CREATE DATABASE "$CATALOG_DB" OWNER "$CATALOG_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$CATALOG_DB')\gexec
  GRANT ALL PRIVILEGES ON DATABASE "$CATALOG_DB" TO "$CATALOG_DB_USER";

  SELECT 'CREATE DATABASE "$ORDER_DB" OWNER "$ORDER_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$ORDER_DB')\gexec
  GRANT ALL PRIVILEGES ON DATABASE "$ORDER_DB" TO "$ORDER_DB_USER";

  SELECT 'CREATE USER "$KEYCLOAK_DB_USER" WITH PASSWORD ''$KEYCLOAK_DB_PASSWORD'''
  WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$KEYCLOAK_DB_USER')\gexec

  SELECT 'CREATE DATABASE "$KEYCLOAK_DB" OWNER "$KEYCLOAK_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$KEYCLOAK_DB')\gexec
  GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB" TO "$KEYCLOAK_DB_USER";
EOSQL
