<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>dev.tuiop</groupId>
  <artifactId>markethub-v2</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>MarketHub-v2</name>
  <url>http://maven.apache.org</url>


  <modules>
    <module>services/account-service</module>
    <module>libs/common-api</module>
    <module>libs/common-events</module>

    <module>services/catalog-service</module>
    <module>services/order-service</module>
    <module>services/cart-service</module>
    <module>services/payment-service</module>
    <module>services/notification-service</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>


</project>
