spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/markethub}

  datasource:
    username: markethub
    password: markethub
    url: jdbc:postgresql://localhost:5432/orders

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8083

services:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
  catalog:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}
  cart:
    url: ${CART_SERVICE_URL:http://localhost:8084}
  payment:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8085}


